#!/usr/bin/env python3
"""
test_write_project_md.py — RED-first tests for write_project_md.py.

CLAUDE.md is now a slim pointer document. Detailed content lives in dedicated
index files generated by the writer. Tests cover:
- IRON_LAWS + GUIDELINES Python SSOT (8 laws, 4 guidelines)
- render_codebase_map_doc = full 4-section map (still --full-claude-md)
- render_claude_md is a minimal pointer (references, not inlined content)
- write_project_md atomic (no .tmp leftover)
- write_project_md also writes AGENTS.md + 4 index files
- write_project_md(full_map=True) writes docs/CODEBASE-MAP.md
- Index writers produce the right content (L1-L8, G1-G4, hook matrix, rules list)
"""
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "lib"))

import write_project_md  # noqa: E402


class TestWriteProjectMd(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)

    def tearDown(self):
        self.tmp.cleanup()

    # --- Python SSOT ---------------------------------------------------------

    def test_iron_laws_count_and_content(self):
        laws = write_project_md.IRON_LAWS
        self.assertEqual(len(laws), 8)
        self.assertIn("verification artifact", laws[0])
        self.assertIn("reproducing", laws[1])
        self.assertIn("completion claim", laws[2])
        self.assertIn("TODO", laws[3])
        self.assertIn("option", laws[4])
        # L6 alpha-declare, L7 alpha-location, L8 prose-trim (issue #263)
        self.assertIn("alpha", laws[5].lower())
        self.assertIn("can't self-impose", laws[6])
        self.assertIn("state-machine", laws[7])

    def test_guidelines_count_and_keywords(self):
        gl = write_project_md.GUIDELINES
        self.assertEqual(len(gl), 4)
        # G1 think-before-coding, G2 simplicity-first, G3 surgical, G4 goal-driven
        self.assertIn("assumptions", gl[0].lower())
        self.assertIn("minimum", gl[1].lower())
        self.assertIn("touch", gl[2].lower())
        self.assertIn("success", gl[3].lower())

    # --- Codebase map doc (--full-claude-md) ---------------------------------

    def test_render_codebase_map_doc_has_4_sections(self):
        full = write_project_md.render_codebase_map_doc(self.root)
        for tag in ("## Tree", "## Manifest", "## External deps", "## Conventions"):
            self.assertIn(tag, full)

    def test_render_stub_section_3_still_lazy(self):
        """The §3 stub helper still exists for back-compat (lazy-loading index)."""
        stub = write_project_md.render_stub_section_3(self.root)
        self.assertIn("package.json", stub)
        self.assertIn("--full-claude-md", stub)
        self.assertNotIn("### Tree (depth 4)", stub)

    # --- CLAUDE.md is a pointer document -------------------------------------

    def test_render_claude_md_references_all_index_files(self):
        md = write_project_md.render_claude_md(self.root)
        # Pointer anchors for the four index.md files
        for path in (
            "iron-laws/index.md",
            "guidelines/index.md",
            "hooks/index.md",
            "rules/index.md",
        ):
            self.assertIn(path, md, f"CLAUDE.md must reference {path}")
        # Pointer for the codebase-map doc
        self.assertIn("docs/CODEBASE-MAP.md", md)
        # Hand-off pointer (active stage lives in .dev-kit/state.json but
        # the model doesn't need to read it; it's for tool/harness use only)
        self.assertIn(".dev-kit/hand-off/", md)
        self.assertNotIn(".dev-kit/state.json", md)

    def test_render_claude_md_no_inline_laws_or_guidelines(self):
        """CLAUDE.md must NOT inline L1-L8 or G1-G4 (lazy-load via index)."""
        md = write_project_md.render_claude_md(self.root)
        for i in range(1, 9):
            self.assertNotIn(
                f"**L{i}**", md, f"CLAUDE.md must not inline L{i} (moved to iron-laws/index.md)"
            )
        for i in range(1, 5):
            self.assertNotIn(
                f"**G{i}**", md, f"CLAUDE.md must not inline G{i} (moved to guidelines/index.md)"
            )

    def test_render_claude_md_no_inline_hook_table(self):
        """CLAUDE.md must NOT inline the hook matrix table (lazy-load via hooks/index.md)."""
        md = write_project_md.render_claude_md(self.root)
        # The hook matrix table contains 'tdd-guard' as a row label
        self.assertNotIn("tdd-guard", md)
        # Stage names also should not appear as column headers in CLAUDE.md
        for stage in ("Bootstrap", "Plan", "Design"):
            self.assertNotIn(stage, md)

    def test_render_claude_md_no_inlined_active_stage(self):
        """CLAUDE.md must NOT inline current_stage / current_step / methodology."""
        md = write_project_md.render_claude_md(self.root, stage="design")
        self.assertNotIn("current_stage: design", md)
        self.assertNotIn("current_step:", md)
        self.assertNotIn("methodology:", md)

    def test_render_claude_md_header_banner(self):
        md = write_project_md.render_claude_md(self.root)
        self.assertIn("AUTO-GENERATED", md)
        self.assertIn("project SSOT pointer", md)

    def test_render_claude_md_is_thin_dispatcher(self):
        """render_claude_md body should be thin — under 40 lines of logic."""
        import inspect
        source = inspect.getsource(write_project_md.render_claude_md)
        logic_lines = [
            line for line in source.splitlines()
            if line.strip() and not line.strip().startswith("#")
        ]
        self.assertLess(len(logic_lines), 40, f"render_claude_md too long: {len(logic_lines)} lines")

    # --- Index renderers -----------------------------------------------------

    def test_render_iron_laws_index_has_all_laws(self):
        out = write_project_md.render_iron_laws_index()
        for i in range(1, 9):
            self.assertIn(f"**L{i}**", out, f"iron-laws/index.md missing L{i}")
        self.assertIn("verification artifact", out)
        self.assertIn("MUST-8", out)

    def test_render_guidelines_index_has_all_guidelines(self):
        out = write_project_md.render_guidelines_index()
        for i in range(1, 5):
            self.assertIn(f"**G{i}**", out, f"guidelines/index.md missing G{i}")
        # Upstream attribution (github user/org name)
        self.assertIn("andrej-karpathy-skills", out)

    def test_render_rules_index_skips_when_no_rules_dir(self):
        """render_rules_index returns empty string when no `rules/` exists."""
        self.assertEqual(write_project_md.render_rules_index(self.root), "")

    def test_render_rules_index_lists_each_rule(self):
        (self.root / "rules").mkdir()
        (self.root / "rules" / "git-workflow.md").write_text(
            "# Git workflow rules\n\n"
            "Worktree + branch discipline. main is sacred.\n"
        )
        (self.root / "rules" / "session-hygiene.md").write_text(
            "# Session hygiene\n\n"
            "Cache and model discipline.\n"
        )
        out = write_project_md.render_rules_index(self.root)
        self.assertIn("git-workflow.md", out)
        self.assertIn("session-hygiene.md", out)
        self.assertIn("Worktree + branch discipline", out)
        self.assertIn("Cache and model discipline", out)

    def test_render_hooks_index_has_matrix_and_shells(self):
        out = write_project_md.render_hooks_index()
        # Matrix table content
        self.assertIn("Hook matrix", out)
        self.assertIn("tdd-guard", out)
        self.assertIn("MUST-13", out)
        # Hook shell reference table content
        self.assertIn("Hook shells", out)
        self.assertIn("`tdd-guard`", out)
        self.assertIn("`bash-guard`", out)
        self.assertIn("`stop-verify`", out)
        # Correct SSOT path (not the misleading 'active-hooks.json')
        self.assertIn(".dev-kit/.active-hooks.json", out)

    # --- Atomic write side-effects -------------------------------------------

    def test_write_atomic(self):
        p = write_project_md.write_project_md(self.root, full_map=False, stage="plan")
        self.assertTrue(p.exists())
        content = p.read_text()
        self.assertIn("AUTO-GENERATED", content)
        # No tmp leftover
        leftover = list(self.root.glob(".CLAUDE.md.*.tmp"))
        self.assertEqual(leftover, [])

    def test_write_also_writes_agents_md_symlink(self):
        write_project_md.write_project_md(self.root, stage="plan")
        agents_path = self.root / "AGENTS.md"
        self.assertTrue(agents_path.exists())
        self.assertTrue(agents_path.is_symlink())
        self.assertEqual(agents_path.readlink(), Path("CLAUDE.md"))
        self.assertEqual(agents_path.resolve(), (self.root / "CLAUDE.md").resolve())

    def test_write_writes_all_four_index_files(self):
        write_project_md.write_project_md(self.root, stage="plan")
        for rel in ("iron-laws/index.md", "guidelines/index.md", "hooks/index.md"):
            self.assertTrue((self.root / rel).exists(), f"missing {rel}")
        # rules/index.md requires rules/ to exist; no rules/ → no file
        self.assertFalse((self.root / "rules" / "index.md").exists())

    def test_write_writes_rules_index_when_rules_dir_exists(self):
        (self.root / "rules").mkdir()
        (self.root / "rules" / "foo.md").write_text("# Foo\n\nbar baz\n")
        write_project_md.write_project_md(self.root, stage="plan")
        rules_index = self.root / "rules" / "index.md"
        self.assertTrue(rules_index.exists())
        self.assertIn("foo.md", rules_index.read_text())

    def test_write_default_emits_codebase_map_stub(self):
        """Default mode emits a stub so CLAUDE.md's link resolves."""
        write_project_md.write_project_md(self.root, full_map=False, stage="plan")
        doc_path = self.root / "docs" / "CODEBASE-MAP.md"
        self.assertTrue(doc_path.exists())
        content = doc_path.read_text()
        # Stub signals opt-in for the full map
        self.assertIn("--full-claude-md", content)
        # Stub does NOT include the full Tree / Manifest sections
        self.assertNotIn("## Tree", content)
        self.assertNotIn("## Manifest", content)
        # CLAUDE.md itself stays a pointer doc
        claude = (self.root / "CLAUDE.md").read_text()
        self.assertIn("iron-laws/index.md", claude)
        self.assertNotIn("### Tree (depth 4)", claude)

    def test_write_full_map_writes_codebase_map_doc(self):
        """--full-claude-md overwrites the stub with the full 4-section map."""
        write_project_md.write_project_md(self.root, full_map=True, stage="plan")
        doc_path = self.root / "docs" / "CODEBASE-MAP.md"
        self.assertTrue(doc_path.exists())
        content = doc_path.read_text()
        self.assertIn("## Tree", content)
        self.assertIn("## Manifest", content)
        # CLAUDE.md itself is still a pointer doc, not the map
        claude = (self.root / "CLAUDE.md").read_text()
        self.assertIn("iron-laws/index.md", claude)
        self.assertNotIn("### Tree (depth 4)", claude)

    def test_write_full_map_overwrites_stub(self):
        """After a default run that emits the stub, --full-claude-md overwrites."""
        write_project_md.write_project_md(self.root, full_map=False, stage="plan")
        stub_path = self.root / "docs" / "CODEBASE-MAP.md"
        self.assertIn("lazy placeholder", stub_path.read_text())
        write_project_md.write_project_md(self.root, full_map=True, stage="plan")
        content = stub_path.read_text()
        self.assertIn("## Tree", content)
        # Stub markers are gone after overwrite
        self.assertNotIn("lazy placeholder", content)

    def test_write_overwrites_cleanly(self):
        write_project_md.write_project_md(self.root, stage="plan")
        write_project_md.write_project_md(self.root, stage="design")
        # Index files are also overwritten cleanly (idempotent)
        iron = (self.root / "iron-laws" / "index.md").read_text()
        self.assertIn("L1", iron)
        self.assertNotIn("STALE", iron)

    def test_codebase_map_doc_filters_credentials_and_dotfiles(self):
        """CODEBASE-MAP.md must not leak `.git/` or `x-access-token:...@` credentials."""
        cred_dir = self.root / "https:"
        cred_dir.mkdir()
        (cred_dir / "x-access-token:fake-pat@github.com").mkdir()
        (self.root / ".git").write_text("gitdir: /tmp/fake/.git/worktrees/x")
        write_project_md.write_project_md(self.root, full_map=True, stage="plan")
        content = (self.root / "docs" / "CODEBASE-MAP.md").read_text()
        self.assertNotIn("x-access-token", content)
        self.assertNotIn("fake-pat", content)
        self.assertNotIn("\n  .git\n", content)
        self.assertNotIn("\n  .git/", content)

    def test_safe_deps_redacts_credentialed_registry_urls(self):
        """_safe_deps must redact x-access-token:...@ URLs in lockfile lines."""
        (self.root / "requirements.txt").write_text(
            "# Sample lockfile\n"
            "--index-url https://x-access-token:fake-pat@pypi.example.com/simple\n"
            "requests==2.31.0\n"
        )
        out = write_project_md._safe_deps(self.root)
        self.assertNotIn("fake-pat", out)
        self.assertNotIn("x-access-token", out)
        self.assertIn("requests==2.31.0", out)


if __name__ == "__main__":
    unittest.main(verbosity=2)
