#!/usr/bin/env python3
"""
state_codec.py — .dev-kit/state.json ↔ hand-off markdown conversion.

Single source of truth for global state. Per MUST-22 dual-source SSOT:
- CLAUDE.md references `.dev-kit/state.json` (slim-pointer CLAUDE.md does NOT inline the stage; the model reads state.json on demand)
- .dev-kit/state.json (machine-readable, atomic write)
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Dict, Optional

# Dual-import so consumer installs that ship `lib/*.py` flat (no
# `__init__.py` in the consumer `lib/`) keep working. Same pattern as
# `lib/active_hooks_codec.py` and `lib/ci_setup.py`.
try:
    from .atomic import (  # type: ignore
        atomic_write_json,
        atomic_write_text,
        now_iso,
        read_json_or_default,
    )
except ImportError:
    from atomic import (  # type: ignore
        atomic_write_json,
        atomic_write_text,
        now_iso,
        read_json_or_default,
    )

SCHEMA_VERSION = "1.0.0"


def read_state(project_root: Path) -> Dict:
    """Read .dev-kit/state.json. Returns default if missing."""
    state_path = project_root / ".dev-kit" / "state.json"
    default: Dict = {
        "schema_version": SCHEMA_VERSION,
        "project": project_root.name,
        "current_stage": "bootstrap",
        "current_step": 1,
        "last_transition_at": now_iso(),
        "hand_off_chain": [],
        "loop_log_path": str(project_root / ".dev-kit" / "loop-log.json"),
        "shortcut_used": None,
        "claude_md_sha": None,
    }
    return read_json_or_default(state_path, default)


def write_state(project_root: Path, state: Dict) -> None:
    """Atomic write to .dev-kit/state.json. POSIX atomic via rename."""
    state["last_transition_at"] = now_iso()
    state["schema_version"] = SCHEMA_VERSION
    atomic_write_json(project_root / ".dev-kit" / "state.json", state)


def transition_stage(
    project_root: Path,
    new_stage: str,
    step: int = 1,
    shortcut: Optional[str] = None,
) -> Dict:
    """Mark stage transition. Updates state + records into hand-off chain."""
    state = read_state(project_root)
    old_stage = state["current_stage"]
    state["current_stage"] = new_stage
    state["current_step"] = step
    state["shortcut_used"] = shortcut
    state["hand_off_chain"].append({
        "from": old_stage,
        "to": new_stage,
        "at": now_iso(),
        "step": step,
    })
    write_state(project_root, state)
    return state


def append_hand_off(project_root: Path, from_stage: str, to_stage: str, goal: str) -> Path:
    """Append hand-off markdown file. Idempotent (no overwrite)."""
    hand_off_dir = project_root / ".dev-kit" / "hand-off"
    hand_off_dir.mkdir(parents=True, exist_ok=True)
    fname = f"{from_stage}→{to_stage}.md"
    path = hand_off_dir / fname
    if path.exists():
        return path  # idempotent
    content = f"""# Hand-off: {from_stage} → {to_stage}

> Auto-generated by `state_codec.transition_stage()` at {now_iso()}.

## §1 Goal
{goal}

## §2 1-line Summary
(전 단계 완료 요약 — AI가 다음 단계 진입 시 자동 작성)

## §3 Open Issues
(none — 모든 gate 통과한 경우)

## §4 Next Stage Trigger
`/dev-kit:{to_stage}` (0-arg). Preamble 자동 주입: `.dev-kit/state.json` + 이 hand-off.
"""
    atomic_write_text(path, content)
    return path


if __name__ == "__main__":
    import sys
    root = Path(os.environ.get("PROJECT_ROOT", "."))
    if len(sys.argv) < 2:
        print("usage: state_codec.py {read|transition|hand-off} ...", file=sys.stderr)
        sys.exit(1)
    cmd = sys.argv[1]
    if cmd == "read":
        print(json.dumps(read_state(root), indent=2, ensure_ascii=False))
    elif cmd == "transition" and len(sys.argv) >= 3:
        new_state = transition_stage(root, sys.argv[2])
        print(json.dumps(new_state, indent=2, ensure_ascii=False))
    elif cmd == "hand-off" and len(sys.argv) >= 5:
        path = append_hand_off(root, sys.argv[2], sys.argv[3], sys.argv[4])
        print(f"wrote {path}")
    else:
        print(f"unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)
